import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Terms of Service",
  description: "The terms that govern your use of ArthaFlow Global.",
  alternates: { canonical: "/terms" },
};

const sections = [
  {
    h: "1. The Service",
    p: "ArthaFlow provides software that helps manufacturers prepare for and manage exports — AI document generation, HS code classification, readiness scoring, buyer discovery, and the Saathi AI advisor. Some features connect you with third-party partners (freight, insurance, trade finance) who provide their services under their own terms.",
  },
  {
    h: "2. Your Account",
    p: "You must provide accurate business information and keep your credentials secure. You are responsible for activity under your account. Accounts are for businesses; you confirm you are authorised to act for the business you register.",
  },
  {
    h: "3. AI-Generated Content",
    p: "Documents, HS classifications, and advice generated by our AI are assistive drafts, not professional legal, customs, or tax advice. You are responsible for reviewing all generated documents before filing or sharing them, and for the accuracy of information you provide. Export compliance obligations remain yours.",
  },
  {
    h: "4. Fees & Plans",
    p: "Paid plans are billed as described on our pricing page. Fees for partner services (freight, insurance, finance) are shown before you commit. We may change plan pricing with advance notice; changes apply from your next billing cycle.",
  },
  {
    h: "5. Acceptable Use",
    p: "You may not use the platform for unlawful trade, sanctioned destinations or parties, misdeclared goods, or to infringe others' rights; we may suspend accounts that do. You may not resell or scrape the service without our written consent.",
  },
  {
    h: "6. Intellectual Property",
    p: "We own the platform and its technology. You own your business data and the documents generated for you. You grant us a licence to process your data to provide and improve the service.",
  },
  {
    h: "7. Liability",
    p: "The service is provided on an as-is basis. To the maximum extent permitted by law, ArthaFlow is not liable for indirect losses, or for outcomes of shipments, customs decisions, buyer transactions, or partner services. Our aggregate liability is limited to the fees you paid us in the preceding 12 months.",
  },
  {
    h: "8. Termination",
    p: "You may stop using the service and request account deletion at any time. We may suspend or terminate accounts for breach of these terms with notice where practicable.",
  },
  {
    h: "9. Governing Law & Contact",
    p: "These terms are governed by the laws of India, with courts at Pune, Maharashtra having jurisdiction. Questions? Write to info@arthaflowglobal.com.",
  },
];

export default function TermsPage() {
  return (
    <div className="mx-auto max-w-[760px] px-6 py-16">
      <h1 className="mb-2 text-3xl font-extrabold tracking-tight text-text-heading">
        Terms of Service
      </h1>
      <p className="mb-10 text-sm text-text-secondary">
        Last updated: July 2026
      </p>
      <p className="mb-8 text-[15px] leading-relaxed text-text-body">
        These terms govern your use of ArthaFlow Global. By creating an account
        or using the platform you agree to them.
      </p>
      {sections.map((s) => (
        <section key={s.h} className="mb-8">
          <h2 className="mb-2 text-lg font-bold text-text-heading">{s.h}</h2>
          <p className="text-[15px] leading-relaxed text-text-body">{s.p}</p>
        </section>
      ))}
    </div>
  );
}
