import type { Metadata } from "next";
import Link from "next/link";
import Image from "next/image";
import { JsonLdScript } from "@/components/arthaflow/json-ld";
import { softwareSchema } from "@/lib/seo/structured-data";
import { Button } from "@/components/ui/button";
import { HoverCard } from "@/components/arthaflow/hover-card";
import { ProgressBar } from "@/components/arthaflow/progress-bar";
import { StaggerGrid, StaggerItem } from "@/components/arthaflow/stagger";
import { MagneticButton } from "@/components/arthaflow/magnetic-button";
import { Globe } from "@/components/arthaflow/globe";
import {
  FileText,
  Search,
  Truck,
  Zap,
  Target,
  Users,
  Folder,
  Shield,
  Check,
  Play,
  TrendingUp,
  Wrench,
  Pill,
  FlaskConical,
  Shirt,
  Leaf,
  Gem,
  ArrowRight,
  Clock,
  Mountain,
} from "lucide-react";

// ── Opportunity section data ──────────────────────────────────────────────────

const exportTimeline = [
  { year: "2014", value: "$318B", muted: true },
  { year: "2024", value: "$821B", current: true },
  { year: "2030", value: "$2T", target: true },
];

const globalComparison = [
  { country: "China",      value: 3500, label: "$3.5T", color: "bg-text-muted/40" },
  { country: "India",      value: 821,  label: "$821B", color: "bg-action-blue",   highlight: true },
  { country: "Vietnam",    value: 370,  label: "$370B", color: "bg-text-muted/40" },
  { country: "Bangladesh", value: 50,   label: "$50B",  color: "bg-text-muted/40" },
];

const growingSectors = [
  { name: "Engineering",  growth: "+18%", icon: <Wrench size={16} />,       bg: "bg-blue-bg",   color: "text-action-blue" },
  { name: "Pharma",       growth: "+15%", icon: <Pill size={16} />,         bg: "bg-green-bg",  color: "text-success" },
  { name: "Chemicals",    growth: "+22%", icon: <FlaskConical size={16} />, bg: "bg-purple-bg", color: "text-purple" },
  { name: "Textiles",     growth: "+9%",  icon: <Shirt size={16} />,        bg: "bg-gold-bg",   color: "text-[#92710A]" },
  { name: "Agri Products",growth: "+12%", icon: <Leaf size={16} />,         bg: "bg-green-bg",  color: "text-success" },
  { name: "Gems & Jewelry",growth: "+7%", icon: <Gem size={16} />,          bg: "bg-blue-bg",   color: "text-action-blue" },
];

const trustBadges = [
  { icon: <Shield size={18} />, title: "Bank Grade Security", desc: "Your data is encrypted and secure", bg: "bg-green-bg", color: "text-success" },
  { icon: <Clock size={18} />, title: "24/7 Expert Support", desc: "We're here whenever you need us", bg: "bg-gold-bg", color: "text-[#92710A]" },
  { icon: <Zap size={18} />, title: "Save Time & Money", desc: "Automate. Simplify. Scale.", bg: "bg-blue-bg", color: "text-action-blue" },
  { icon: <Mountain size={18} />, title: "Grow Globally", desc: "We take you beyond boundaries", bg: "bg-red-bg", color: "text-error" },
];

const problems = [
  {
    icon: <FileText size={24} />,
    title: "Documentation Nightmare",
    desc: "IEC, HS codes, shipping bills, certificates — a maze most can't navigate.",
    bg: "bg-blue-bg",
    color: "text-action-blue",
  },
  {
    icon: <Search size={24} />,
    title: "No Buyer Access",
    desc: "Zero visibility into who's buying, where, or how to reach them.",
    bg: "bg-gold-bg",
    color: "text-[#92710A]",
  },
  {
    icon: <Truck size={24} />,
    title: "Logistics Overwhelm",
    desc: "Freight, customs, insurance, incoterms — 15+ decisions per shipment.",
    bg: "bg-green-bg",
    color: "text-success",
  },
];

const steps = [
  { n: "1", title: "Onboard Your Business", desc: "Register, upload docs, add products in 10 minutes", color: "bg-action-blue" },
  { n: "2", title: "AI Generates Documents", desc: "Product sheets, HS codes, invoices — generated in seconds", color: "bg-action-blue" },
  { n: "3", title: "We Find Buyers & Ship", desc: "Matched with verified buyers, logistics handled end-to-end", color: "bg-action-blue" },
  { n: "check", title: "Get Paid in Dollars", desc: "Secure international payments to your bank account", color: "bg-success" },
];

const features = [
  { icon: <Zap size={20} />, title: "AI Document Generator", desc: "Product sheets, HS codes, proforma invoices generated by AI in 30 seconds", bg: "bg-blue-bg", color: "text-action-blue" },
  { icon: <Target size={20} />, title: "Export Readiness Score", desc: "Gamified 100-point score tracks your compliance and export preparedness", bg: "bg-gold-bg", color: "text-[#92710A]" },
  { icon: <Users size={20} />, title: "Buyer Matching", desc: "Curated international buyer connections from verified trade channels", bg: "bg-green-bg", color: "text-success" },
  { icon: <Truck size={20} />, title: "Logistics Orchestration", desc: "Freight quotes, customs, insurance — coordinated through partner network", bg: "bg-purple-bg", color: "text-purple" },
  { icon: <Folder size={20} />, title: "Document Vault", desc: "Secure cloud storage for all certificates, licenses, and generated documents", bg: "bg-blue-bg", color: "text-action-blue" },
  { icon: <Shield size={20} />, title: "Compliance Tracker", desc: "Step-by-step IEC registration, AD code setup, DGFT compliance guidance", bg: "bg-gold-bg", color: "text-[#92710A]" },
];

export const metadata: Metadata = {
  // Leads on the problem rather than the company: the searcher does not know
  // our name yet, they know they cannot export.
  title:
    "Export Infrastructure for Indian Manufacturers — HS Codes, Documents, Markets",
  description:
    "India has 57M+ MSMEs and fewer than 0.3% export. ArthaFlow classifies your HS code, generates every export document, and shows you which markets want your product.",
  alternates: { canonical: "/" },
};

export default function HomePage() {
  return (
    <>
      <JsonLdScript data={softwareSchema} />
      {/* GLOBE HERO */}
      <section className="relative overflow-hidden bg-navy">
        <div className="relative mx-auto max-w-[840px] px-6 pt-14 sm:px-8">
          {/* Value proposition — the first thing a visitor reads */}
          <div className="relative z-10 flex flex-col items-center text-center">
            <div className="mb-4 text-xs font-bold uppercase tracking-[2px] text-artha-gold">
              Tech-Enabled Export Infrastructure
            </div>
            <h1 className="mb-4 max-w-[720px] text-4xl font-extrabold leading-[1.08] tracking-tight text-white drop-shadow-[0_4px_30px_rgba(0,0,0,0.5)] sm:text-6xl">
              Your Export Department —{" "}
              <span className="text-artha-gold">Without The Overhead</span>
            </h1>
            <p className="mb-7 max-w-[540px] text-base leading-relaxed text-white/70 sm:text-lg">
              India has 57M+ MSMEs and fewer than 0.3% export. We classify your
              HS code, generate every export document, and show you which
              markets actually want your product.
            </p>
            <div className="flex flex-wrap items-center justify-center gap-4">
              <MagneticButton>
                <Link href="/login">
                  <Button size="lg" className="bg-artha-gold text-navy hover:bg-artha-gold/90">
                    Start Exporting Free
                  </Button>
                </Link>
              </MagneticButton>
              <MagneticButton strength={0.2}>
                {/* Better second action than pricing, which is already in the
                    nav: this one proves the product works before asking for
                    anything. */}
                <Link href="/calculator">
                  <Button size="lg" variant="outline" className="border-white/50 bg-white/10 text-white hover:bg-white/20 hover:border-white/70">
                    Try the free calculator
                  </Button>
                </Link>
              </MagneticButton>
              <MagneticButton strength={0.2}>
                <Link href="/hsn-search">
                  <Button size="lg" variant="outline" className="border-white/50 bg-white/10 text-white hover:bg-white/20 hover:border-white/70">
                    Search HSN codes
                  </Button>
                </Link>
              </MagneticButton>
            </div>
            <p className="mt-5 text-[13px] text-white/55">
              Live with 5 pilot manufacturers in Mumbai and Pune
            </p>
          </div>

          {/* Globe — bottom cropped */}
          <div className="relative mx-auto -mt-6 max-w-[720px]" style={{ marginBottom: "-42%" }}>
            <Globe />
          </div>
        </div>
      </section>

      {/* TRUST BAR — reassurance strip right under the fold, before the ask */}
      <section className="border-t border-white/10 bg-navy px-6 py-6 sm:px-8">
        <div className="mx-auto grid max-w-[1200px] grid-cols-1 gap-6 divide-y divide-white/10 sm:grid-cols-2 sm:gap-0 sm:divide-y-0 lg:grid-cols-4">
          {trustBadges.map((b, i) => (
            <div
              key={b.title}
              className={`flex items-center gap-3 pt-6 first:pt-0 sm:pt-0 lg:px-6 lg:first:pl-0 ${
                i > 0 ? "lg:border-l lg:border-white/10" : ""
              }`}
            >
              <div className={`flex h-10 w-10 shrink-0 items-center justify-center rounded-lg ${b.bg} ${b.color}`}>
                {b.icon}
              </div>
              <div>
                <div className="text-[13px] font-bold text-white">{b.title}</div>
                <div className="text-[12px] text-white/60">{b.desc}</div>
              </div>
            </div>
          ))}
        </div>
      </section>

      {/* HERO */}
      <section className="relative overflow-hidden bg-gradient-to-br from-navy to-royal-blue px-8 py-20">
        <div className="absolute -right-20 -top-30 h-[400px] w-[400px] rounded-full bg-[radial-gradient(circle,rgba(212,168,67,0.12),transparent_70%)]" />
        <div className="absolute -bottom-40 -left-24 h-[460px] w-[460px] rounded-full bg-[radial-gradient(circle,rgba(37,99,235,0.18),transparent_70%)]" />
        <div className="relative mx-auto grid max-w-[1200px] items-center gap-14 lg:grid-cols-[1.1fr_0.9fr]">
          <div>
            <h2 className="mb-5 max-w-[620px] text-[2rem] font-extrabold leading-[1.08] tracking-tight text-white sm:text-[2.5rem]">
              One Dashboard for the{" "}
              <span className="text-artha-gold">Entire Export Journey</span>
            </h2>
            <p className="mb-9 max-w-[540px] text-lg leading-relaxed text-white/70">
              Readiness scoring, AI-generated documents, buyer inquiries, and
              live shipment tracking — everything your export business needs,
              in one place.
            </p>
            <div className="flex flex-wrap gap-4">
              <MagneticButton strength={0.2}>
                <Link href="/login">
                  <Button size="lg" variant="outline" className="border-white/50 bg-white/10 text-white hover:bg-white/20 hover:border-white/70">
                    <Play size={18} />
                    See It In Action
                  </Button>
                </Link>
              </MagneticButton>
            </div>
          </div>

          {/* Dashboard mockup */}
          <div className="hidden lg:block">
            <div className="rounded-2xl border border-white/12 bg-white/6 p-4.5 shadow-[0_30px_60px_rgba(0,0,0,0.4)] backdrop-blur-sm [transform:perspective(1200px)_rotateY(-8deg)_rotateX(4deg)]">
              <div className="overflow-hidden rounded-[10px] bg-card">
                <div className="flex h-9 items-center bg-navy px-3.5">
                  <span className="text-[13px] font-extrabold text-artha-gold">
                    ArthaFlow
                  </span>
                </div>
                <div className="p-4">
                  <div className="mb-3 text-[13px] font-bold text-text-heading">
                    Export Readiness
                  </div>
                  <div className="mb-3.5 grid grid-cols-2 gap-2">
                    {[
                      ["87", "Readiness", "text-action-blue"],
                      ["3", "Inquiries", "text-[#92710A]"],
                      ["12", "Docs", "text-[#047857]"],
                      ["2", "Shipments", "text-purple"],
                    ].map(([val, label, color], i) => (
                      <div key={i} className="rounded-lg bg-subtle p-2">
                        <div className={`font-mono text-xl font-bold tabular-nums ${color}`}>{val}</div>
                        <div className="text-[10px] text-text-secondary">
                          {label}
                        </div>
                      </div>
                    ))}
                  </div>
                  {[
                    ["IEC Registered", 100, "bg-success"],
                    ["Product Catalogue", 75, "bg-artha-gold"],
                    ["Certifications", 50, "bg-artha-gold"],
                  ].map(([label, pct, color], i) => (
                    <div key={i} className="mb-2">
                      <div className="mb-0.5 flex justify-between text-[10px]">
                        <span className="text-text-body">{label as string}</span>
                        <span className={`font-mono font-semibold tabular-nums ${color === "bg-success" ? "text-[#047857]" : "text-[#92710A]"}`}>
                          {pct as number}%
                        </span>
                      </div>
                      <ProgressBar value={pct as number} color={color as string} height={4} />
                    </div>
                  ))}
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* OPPORTUNITY — compact, info-dense */}
      <section className="bg-card px-8 py-20">
        <div className="mx-auto max-w-[1100px]">
          {/* Header */}
          <div className="mb-10 flex flex-col items-center text-center">
            <h2 className="mb-2.5 text-[2rem] font-extrabold tracking-tight text-text-heading sm:text-[2.5rem]">
              India is at an Export Inflection Point
            </h2>
            <p className="max-w-[560px] text-[15px] text-text-secondary">
              Government targeting <span className="font-semibold text-text-body">$2 trillion</span> in
              exports by 2030 — but only 0.3% of MSMEs participate today.
            </p>
          </div>

          {/* Timeline strip */}
          <div className="mb-10 rounded-xl border border-border bg-card p-5 shadow-sm">
            <div className="mb-3 flex items-center justify-center gap-1.5 text-[11px] font-bold uppercase tracking-wider text-text-muted">
              <TrendingUp size={13} className="text-action-blue" />
              India&apos;s Export Trajectory
            </div>
            <div className="flex items-center justify-between gap-2 sm:gap-6">
              {exportTimeline.map((t, i) => (
                <div key={t.year} className="flex flex-1 items-center">
                  <div className="flex-1 text-center">
                    <div
                      className={`font-mono text-2xl font-extrabold tabular-nums tracking-tight sm:text-3xl ${
                        t.target
                          ? "text-[#92710A]"
                          : t.current
                            ? "text-action-blue"
                            : "text-text-muted"
                      }`}
                    >
                      {t.value}
                    </div>
                    <div className="mt-0.5 text-xs font-medium text-text-secondary">
                      {t.year}
                      {t.target && (
                        <span className="ml-1.5 rounded bg-gold-bg px-1.5 py-0.5 text-[10px] font-bold text-[#6B5208]">
                          TARGET
                        </span>
                      )}
                    </div>
                  </div>
                  {i < exportTimeline.length - 1 && (
                    <ArrowRight size={16} className="shrink-0 text-text-muted" />
                  )}
                </div>
              ))}
            </div>
          </div>

          {/* Two-column grid: comparison + sectors */}
          <div className="grid grid-cols-1 gap-5 lg:grid-cols-[1.1fr_1fr]">
            {/* LEFT — Global comparison */}
            <div className="rounded-xl border border-border bg-card p-6 shadow-sm">
              <div className="mb-1 text-[15px] font-bold text-text-heading">
                Where India Stands Globally
              </div>
              <p className="mb-5 text-[13px] text-text-secondary">
                5th largest exporter — but the gap from leaders means runway, not ceiling.
              </p>
              <div className="flex flex-col gap-3.5">
                {globalComparison.map((c) => {
                  const pct = (c.value / 3500) * 100;
                  return (
                    <div key={c.country}>
                      <div className="mb-1 flex items-center justify-between">
                        <span
                          className={`text-[13px] font-semibold ${
                            c.highlight ? "text-action-blue" : "text-text-body"
                          }`}
                        >
                          {c.country}
                        </span>
                        <span
                          className={`font-mono text-xs font-bold tabular-nums ${
                            c.highlight ? "text-action-blue" : "text-text-secondary"
                          }`}
                        >
                          {c.label}
                        </span>
                      </div>
                      <div className="h-2 overflow-hidden rounded-full bg-subtle">
                        <div
                          className={`h-full rounded-full ${c.color} transition-all`}
                          style={{ width: `${pct}%` }}
                        />
                      </div>
                    </div>
                  );
                })}
              </div>
            </div>

            {/* RIGHT — Growing sectors */}
            <div className="rounded-xl border border-border bg-card p-6 shadow-sm">
              <div className="mb-1 text-[15px] font-bold text-text-heading">
                Sectors Driving Growth
              </div>
              <p className="mb-5 text-[13px] text-text-secondary">
                YoY export growth — find where your products fit.
              </p>
              <div className="grid grid-cols-2 gap-2.5 sm:grid-cols-3">
                {growingSectors.map((s) => (
                  <div
                    key={s.name}
                    className="flex flex-col items-start gap-1.5 rounded-lg border border-subtle bg-background p-3 transition-colors hover:border-action-blue hover:bg-hover-blue"
                  >
                    <div
                      className={`flex h-7 w-7 items-center justify-center rounded-md ${s.bg} ${s.color}`}
                    >
                      {s.icon}
                    </div>
                    <div className="text-[12.5px] font-semibold leading-tight text-text-heading">
                      {s.name}
                    </div>
                    <div className="font-mono text-[11px] font-bold tabular-nums text-[#047857]">
                      {s.growth} YoY
                    </div>
                  </div>
                ))}
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* PROBLEM */}
      <section className="bg-background px-8 py-20">
        <div className="mx-auto max-w-[1200px]">
          <div className="mb-12 text-center">
            <h2 className="mb-3 text-[2rem] font-extrabold tracking-tight text-text-heading sm:text-[2.5rem]">
              99.7% of Indian Manufacturers Don&apos;t Export
            </h2>
            <p className="mx-auto max-w-[560px] text-[17px] text-text-secondary">
              Not because their products aren&apos;t good enough — because the
              infrastructure doesn&apos;t exist.
            </p>
          </div>
          <StaggerGrid
            inView
            className="grid grid-cols-1 gap-6 sm:grid-cols-2 lg:grid-cols-3"
          >
            {problems.map((p, i) => (
              <StaggerItem key={i}>
                <HoverCard>
                  <div
                    className={`mb-4 flex h-12 w-12 items-center justify-center rounded-xl ${p.bg} ${p.color}`}
                  >
                    {p.icon}
                  </div>
                  <h3 className="mb-2 text-[17px] font-bold text-text-heading">
                    {p.title}
                  </h3>
                  <p className="text-sm leading-relaxed text-text-secondary">
                    {p.desc}
                  </p>
                </HoverCard>
              </StaggerItem>
            ))}
          </StaggerGrid>
        </div>
      </section>

      {/* HOW IT WORKS */}
      <section className="bg-card px-8 py-20" id="how-it-works">
        <div className="mx-auto max-w-[1200px]">
          <div className="mb-14 text-center">
            <h2 className="text-2xl font-bold tracking-tight text-text-heading sm:text-3xl">
              From Factory Floor to International Payment in 4 Steps
            </h2>
          </div>
          <div className="grid grid-cols-1 gap-4 sm:grid-cols-2 lg:grid-cols-4">
            {steps.map((s, i) => (
              <div key={i} className="relative text-center">
                {i < 3 && (
                  <div className="absolute left-1/2 top-7 hidden h-0.5 w-full bg-border lg:block" />
                )}
                <div
                  className={`relative z-10 mx-auto mb-5 flex h-14 w-14 items-center justify-center rounded-full font-mono text-[22px] font-bold tabular-nums text-white shadow-lg ${s.color}`}
                >
                  {s.n === "check" ? <Check size={26} /> : s.n}
                </div>
                <h3 className="mb-1.5 text-[17px] font-bold text-text-heading">
                  {s.title}
                </h3>
                <p className="mx-auto max-w-[220px] text-[13px] leading-snug text-text-secondary">
                  {s.desc}
                </p>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* FEATURES */}
      <section className="bg-background px-8 py-20">
        <div className="mx-auto max-w-[1200px]">
          <div className="mb-12 text-center">
            <h2 className="text-2xl font-bold tracking-tight text-text-heading sm:text-3xl">
              Everything You Need to Export — In One Platform
            </h2>
          </div>
          <StaggerGrid
            inView
            className="grid grid-cols-1 gap-6 sm:grid-cols-2 lg:grid-cols-3"
          >
            {features.map((f, i) => (
              <StaggerItem key={i}>
                <HoverCard>
                  <div
                    className={`mb-4 flex h-11 w-11 items-center justify-center rounded-[10px] ${f.bg} ${f.color}`}
                  >
                    {f.icon}
                  </div>
                  <h3 className="mb-2 text-[17px] font-bold text-text-heading">
                    {f.title}
                  </h3>
                  <p className="text-sm leading-relaxed text-text-secondary">
                    {f.desc}
                  </p>
                </HoverCard>
              </StaggerItem>
            ))}
          </StaggerGrid>
        </div>
      </section>

      {/* FINAL CTA — replaces the old testimonial + "Ready to Start
          Exporting?" band. One closing moment instead of two near-identical
          dark sections back to back. Background is a real port photograph
          (public/port-dusk-hero.webp), not a stock category shot — served
          through next/image so Next.js's built-in optimizer (sharp) emits
          right-sized WebP/AVIF per viewport from the single source file.
          Source is WebP, not PNG: the original PNG export was 7.2MB (a
          lossless format on a photograph), WebP q90 is 0.61MB at visually
          identical quality — the optimizer was re-deriving WebP from that
          bloated PNG on every uncached request. */}
      <section className="relative isolate flex min-h-[480px] items-center overflow-hidden px-8 py-20 sm:min-h-[560px]">
        <Image
          src="/port-dusk-hero.webp"
          alt=""
          fill
          priority={false}
          sizes="100vw"
          className="-z-10 object-cover"
        />
        {/* Left-weighted dark wash: photo stays legible as a photo on the
            right, text sits on a near-solid navy field on the left — the
            same balance as the reference this section was built from. */}
        <div className="absolute inset-0 -z-10 bg-gradient-to-r from-navy via-navy/85 to-navy/30" />

        <div className="relative mx-auto w-full max-w-[1200px]">
          <div className="max-w-[600px]">
            <h2 className="mb-5 text-[2rem] font-extrabold leading-[1.15] tracking-tight text-white sm:text-[2.75rem]">
              Your Next Customer Isn&apos;t in Your City.{" "}
              <span className="text-artha-gold">
                They&apos;re Somewhere Across the World.
              </span>
            </h2>
            <MagneticButton>
              <Link href="/login">
                <Button size="lg" className="gap-1.5 bg-artha-gold text-navy hover:bg-artha-gold/90">
                  Start Exporting Today <ArrowRight size={17} />
                </Button>
              </Link>
            </MagneticButton>
            <p className="mt-4 text-[13px] text-white/65">
              No credit card required · Setup in 10 minutes
            </p>
          </div>
        </div>
      </section>
    </>
  );
}
